Repository Vishakhasarode/ProfileCards, pull requests merged in 2023-10, with the labels that each got.

#1 created an form for taking user data
  form.html
Labels: enhancement, help wanted, good first issue

#2 Revert "created an form for taking user data"
  form.html
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2023

#4 updated
  form.html
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2023

#7 fixed banner
  index.html
  temp.html
  temp1.html
Labels: help wanted, good first issue, hacktoberfest-accepted, hacktoberfest2023
